const PORTFOLIO = {
  commercial: [
    { slug: "shokz-directors-cut", title: "Shokz (directors cut)", video: "https://www.youtube.com/embed/7nTOkXUMWZY", type: "youtube", cover: "/covers/shokz-directors-cut.webm" },
    { slug: "asco-sound-of-progress", title: "ASCO - Sound of Progress", video: "https://player.vimeo.com/video/710483743", type: "vimeo", cover: "/covers/asco-sound-of-progress.webm" },
    { slug: "best-buy", title: "Best Buy", video: "https://fast.wistia.net/embed/iframe/pv6df2jktj", type: "wistia", cover: "/covers/best-buy.webm" },
    { slug: "pga2k-nsw2", title: "PGA2K- Tiger", video: "https://player.vimeo.com/video/1h150499022", type: "vimeo", cover: "/covers/pga2k-nsw2.webm" },
    { slug: "delloitte-brand-film", title: "Delloitte Brand Film", video: "https://fast.wistia.net/embed/iframe/rihr0ex733", type: "wistia", cover: "/covers/delloitte-brand-film.webm" },
    { slug: "connecticut-lottery-keno-yeah", title: "CONNECTICUT LOTTERY KENO YEAH", video: "https://player.vimeo.com/video/1013596748", type: "vimeo", cover: "/covers/connecticut-lottery-keno-yeah.webm" },
    { slug: "country-crock", title: "Country Crock", video: "https://player.vimeo.com/video/696812977", type: "vimeo", cover: "/covers/country-crock.webm" },
    { slug: "dietz-and-watson", title: "Dietz and Watson", video: "https://player.vimeo.com/video/630572467", type: "vimeo", cover: "/covers/dietz-and-watson.webm" },
    { slug: "best-buy-mess-up", title: "Best Buy - Mess Up", video: "https://fast.wistia.net/embed/iframe/fbggvtws70", type: "wistia", coverImage: "/covers/best-buy-mess-up.jpg" },
    { slug: "get-there-florida-education", title: "Get There - Florida Education", video: "https://player.vimeo.com/video/617113397", type: "vimeo", cover: "/covers/get-there-florida-education.webm" },
    { slug: "microsoft-edge-holiday", title: "Microsoft Edge Holiday", video: "https://fast.wistia.net/embed/iframe/vp6voe2xso", type: "wistia", cover: "/covers/microsoft-edge-holiday.webm" },
    { slug: "ryerson-insurance", title: "Ryerson Insurance", video: "https://player.vimeo.com/video/639725079", type: "vimeo", cover: "/covers/ryerson-insurance.webm" },
    { slug: "spinbrush", title: "Spinbrush", video: "https://fast.wistia.net/embed/iframe/d5ww5vfasl", type: "wistia", cover: "/covers/spinbrush.webm" },
    { slug: "sherlock-homes", title: "Sherlock Homes", video: "https://www.youtube.com/embed/dRBpizr3PCM", type: "youtube", cover: "/covers/sherlock-homes.webm" },
    { slug: "defy-the-odds", title: "Defy The Odds", video: "https://player.vimeo.com/video/667398721", type: "vimeo", cover: "/covers/defy-the-odds.webm" },
    { slug: "brave-girl-embrace-grace", title: "'Brave Girl' Embrace Grace", video: "https://player.vimeo.com/video/861404679", type: "vimeo", coverImage: "" },
    { slug: "aaa", title: "AAA", video: "https://player.vimeo.com/video/639342583", type: "vimeo", coverImage: "" },
    { slug: "marshalls-activewear-15s", title: "Marshalls \"Activewear\" 15s", video: "https://player.vimeo.com/video/867277742", type: "vimeo", coverImage: "/covers/marshalls-activewear-15s.jpg" },
    { slug: "top-golf", title: "Top Golf", video: "https://player.vimeo.com/video/738006171", type: "vimeo", cover: "/covers/top-golf.webm" },
    { slug: "hammerhead", title: "Hammerhead", video: "https://player.vimeo.com/video/454148137", type: "vimeo", coverImage: "" },
    { slug: "rba-the-light-stays-on", title: "RBA - The Light Stays On", video: "https://player.vimeo.com/video/708017846", type: "vimeo", coverImage: "" },
    { slug: "middlesex-hospital", title: "Middlesex Hospital", video: "https://player.vimeo.com/video/680629442", type: "vimeo", cover: "/covers/middlesex-hospital.webm" },
    { slug: "vans-heaven", title: "Vans - Heaven", video: "https://www.youtube.com/embed/_2e9hdyEomI", type: "youtube", cover: "/covers/vans-heaven.webm" },
    { slug: "peerspace", title: "Peerspace", video: "https://player.vimeo.com/video/1036602916", type: "vimeo", coverImage: "/covers/peerspace.jpg" },
    { slug: "middlesex-health-the-boat", title: "Middlesex Health - The Boat", video: "https://player.vimeo.com/video/884897404", type: "vimeo", cover: "/covers/middlesex-health-the-boat.webm" },
    { slug: "ucare-diana", title: "UCare - Diana", video: "https://player.vimeo.com/video/884861251", type: "vimeo", cover: "/covers/ucare-diana.webm" },
    { slug: "wawa", title: "WAWA", video: "https://player.vimeo.com/video/1072106602", type: "vimeo", cover: "/covers/wawa.webm" },
    { slug: "dr-sheffields", title: "Dr. Sheffields", video: "https://player.vimeo.com/video/349157045", type: "vimeo", cover: "/covers/dr-sheffields.webm" },
    { slug: "jeep", title: "Jeep", video: "https://player.vimeo.com/video/373308699", type: "vimeo", cover: "/covers/jeep.webm" },
    { slug: "keurig", title: "Keurig", video: "https://fast.wistia.net/embed/iframe/craqv82le1", type: "wistia", cover: "/covers/keurig.webm" },
    { slug: "aaa-seriously-golf", title: "AAA Seriously - Golf", video: "https://player.vimeo.com/video/630160010", type: "vimeo", coverImage: "" },
    { slug: "hartford-athletic", title: "Hartford Athletic - Soccer City", video: "https://player.vimeo.com/video/304629666", type: "vimeo", coverImage: "/covers/hartford-athletic.jpg" },
    { slug: "discover-the-tuscan-olive-trees-growing-in-california", title: "Discover the Tuscan Olive Trees Growing in California", video: "https://www.youtube.com/embed/dDVbwwbh05A", type: "youtube", coverImage: "/covers/discover-the-tuscan-olive-trees-growing-in-california.jpg" }
  ],
  musicVideo: [
    { slug: "sierra-spirit-ghost-official-music-video", title: "Sierra Spirit - ghost (Official Music Video)", video: "https://www.youtube.com/embed/FIBOxj25jaE", type: "youtube" , coverImage: ""},
    { slug: "spittn-chiclets", title: "Spittn' Chiclets", video: "https://www.youtube.com/embed/pBGodH4bx3Y", type: "youtube" , coverImage: ""},
    { slug: "dead-emerson-eleventh-hour", title: "Dead Emerson - Eleventh Hour", video: "https://www.youtube.com/embed/Yxu_84QCbkA", type: "youtube" , cover: "/covers/dead-emerson-eleventh-hour.webm"},
    { slug: "karma-a-will-away", title: "Karma - A Will Away", video: "https://www.youtube.com/embed/s5g-DCxmX20", type: "youtube" , cover: "/covers/karma-a-will-away.webm"},
    { slug: "des-rocks-imaginary-friends", title: "Des Rocks - Imaginary Friends", video: "https://www.youtube.com/embed/BhRvU9IqQpU", type: "youtube" , coverImage: ""},
    { slug: "mitchel-dae-innocent-live", title: "Mitchel Dae -Innocent live", video: "https://www.youtube.com/embed/HkgAchzbrHY", type: "youtube" , coverImage: ""}
  ],
  doc: [
    { slug: "chris-brickley-x-red-bull", title: "Chris Brickley x Red Bull", video: "https://player.vimeo.com/video/372786655", type: "vimeo" , coverImage: ""},
    { slug: "new-tribe-rising", title: "New Tribe Rising", video: "https://player.vimeo.com/video/286334354", type: "vimeo" , coverImage: "/covers/new-tribe-rising.jpg"},
    { slug: "discover-the-tuscan-olive-trees-growing-in-california", title: "Discover the Tuscan Olive Trees Growing in California", video: "https://www.youtube.com/embed/dDVbwwbh05A", type: "youtube" , coverImage: "/covers/discover-the-tuscan-olive-trees-growing-in-california.jpg"}
  ]
};
